# Docker Compose untuk Object Detection App

services:
  objectdetection:
    build: .
    container_name: objectdetection-app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount untuk cache model agar tidak perlu download ulang
      - model_cache:/app/.cache
      # Mount untuk logs (opsional)
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Resource limits (sesuaikan dengan kapasitas server Anda)
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

volumes:
  model_cache:
    driver: local
