[phases.setup]
nixPkgs = ["python39", "gcc", "pkg-config", "libjpeg", "zlib"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn wsgi:app --bind 0.0.0.0:$PORT" 